<?php

// ---------------------------------------------------------------------------
//  AUTHENTICATION GATE — added 2026-08-30.
//  This endpoint writes and was reachable by an anonymous caller. Confirmed by probing:
//  it executed its handler for an unauthenticated GET rather than refusing.
// ---------------------------------------------------------------------------
require_once __DIR__ . '/../../_runtime/guard.php';
guard_require_auth();
/**
 * @file SITE-ROOT/admin/ajax/font_handler.php
 * @version 2025.08.10 (Fixed)
 * @description Handles uploading, deleting, and listing custom server fonts.
 */
require_once dirname(__DIR__, 3) . '/auth.php';
requireAuth();

header('Content-Type: application/json');

$fontsDir = SITE_ROOT . '/media/fonts/';
$cssFile = SITE_ROOT . '/css/custom-fonts.css';

if (!is_dir($fontsDir)) {
    mkdir($fontsDir, 0755, true);
}

$action = $_REQUEST['action'] ?? null;

// --- Main Action Router ---
switch ($action) {
    case 'upload': handle_upload(); break;
    case 'list': handle_list(); break;
    case 'delete': handle_delete(); break;
    default: echo json_encode(['success' => false, 'message' => 'Invalid action.']);
}

function handle_upload() {
    global $fontsDir;
    if (empty($_FILES['fonts'])) {
        echo json_encode(['success' => false, 'message' => 'No files were uploaded.']);
        return;
    }

    $uploaded = 0;
    foreach ($_FILES['fonts']['tmp_name'] as $index => $tmp_name) {
        if ($_FILES['fonts']['error'][$index] === UPLOAD_ERR_OK) {
            $filename = basename($_FILES['fonts']['name'][$index]); // Using basename for security
            $destination = $fontsDir . $filename;
            if (move_uploaded_file($tmp_name, $destination)) {
                $uploaded++;
            }
        }
    }

    if ($uploaded > 0) {
        update_css_file();
        echo json_encode(['success' => true, 'message' => "$uploaded font file(s) uploaded successfully."]);
    } else {
        echo json_encode(['success' => false, 'message' => 'File upload failed. Check server permissions.']);
    }
}

function handle_list() {
    echo json_encode(['success' => true, 'fonts' => parse_css_for_fonts()]);
}

function handle_delete() {
    global $fontsDir;
    $fontFamilyToDelete = $_POST['fontFamily'] ?? '';
    if (empty($fontFamilyToDelete)) {
        echo json_encode(['success' => false, 'message' => 'No font family specified for deletion.']);
        return;
    }

    $files = array_diff(scandir($fontsDir), ['.', '..']);
    $deletedCount = 0;
    foreach ($files as $file) {
        $font_name_from_file = preg_replace('/\.(ttf|woff|woff2)$/i', '', $file);
        $font_name_from_file = str_replace(['_', '-'], ' ', $font_name_from_file);
        $font_name_from_file = ucwords(strtolower($font_name_from_file));
        if ($font_name_from_file === $fontFamilyToDelete) {
            if (unlink($fontsDir . $file)) {
                $deletedCount++;
            }
        }
    }

    update_css_file();
    echo json_encode(['success' => true, 'message' => "Deleted {$deletedCount} file(s) for font '{$fontFamilyToDelete}'."]);
}

function parse_css_for_fonts() {
    global $cssFile;
    $fonts = [];
    if (file_exists($cssFile)) {
        $content = file_get_contents($cssFile);
        preg_match_all("/font-family: '([^']+)';/", $content, $matches);
        if (!empty($matches[1])) {
            foreach (array_unique($matches[1]) as $fontFamily) {
                $fonts[] = ['fontFamily' => $fontFamily];
            }
        }
    }
    return $fonts;
}


// =========== FIXED FUNCTION STARTS HERE ===========
function update_css_file() {
    global $fontsDir, $cssFile;
    $files = array_diff(scandir($fontsDir), ['.', '..']);
    $css_content = "/**\n * @file SITE-ROOT/css/custom-fonts.css\n * @version " . date('Y.m.d.His') . "\n * @description Auto-generated by the Font Manager.\n */\n\n";

    // --- FIX START: Determine the correct root-relative path ---
    // This calculates the path from the web root to the site's base directory.
    // It gracefully handles being in the root ('/') or a subdirectory ('/mysite/').
    $site_path = str_replace($_SERVER['DOCUMENT_ROOT'], '', str_replace('\\', '/', SITE_ROOT));
    if (substr($site_path, -1) !== '/') {
        $site_path .= '/';
    }
    $font_url_path = $site_path . 'fonts/';
    // --- FIX END ---

    $font_families = [];
    foreach ($files as $file) {
        $path = $fontsDir . $file;
        $ext = strtolower(pathinfo($path, PATHINFO_EXTENSION));
        if (in_array($ext, ['ttf', 'woff', 'woff2'])) {
            $font_name = preg_replace('/\.(ttf|woff|woff2)$/i', '', $file);
            $font_name = str_replace(['_', '-'], ' ', $font_name);
            $font_name = ucwords(strtolower($font_name));
            $font_families[$font_name][$ext] = $file;
        }
    }

    foreach ($font_families as $name => $formats) {
        $css_content .= "@font-face {\n";
        $css_content .= "    font-family: '{$name}';\n";
        $sources = [];
        // --- FIX START: Use the new root-relative path variable ---
        if (isset($formats['woff2'])) $sources[] = "url('{$font_url_path}{$formats['woff2']}') format('woff2')";
        if (isset($formats['woff']))  $sources[] = "url('{$font_url_path}{$formats['woff']}') format('woff')";
        if (isset($formats['ttf']))   $sources[] = "url('{$font_url_path}{$formats['ttf']}') format('truetype')";
        // --- FIX END ---
        $css_content .= "    src: " . implode(",\n         ", $sources) . ";\n";
        $css_content .= "    font-weight: normal;\n";
        $css_content .= "    font-style: normal;\n";
        $css_content .= "}\n\n";
    }

    file_put_contents($cssFile, $css_content, LOCK_EX);
}
// =========== FIXED FUNCTION ENDS HERE ===========
?>